"""
Django settings for DATABIOS project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
import os

# Load environment variables from .env file if it exists
try:
    from dotenv import load_dotenv
    # Load from repository root or current directory
    load_dotenv(os.path.join(Path(__file__).resolve().parent.parent.parent, '.env'))
    load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-aj&4!^je=yes)oxi0mf9*u)p9)5++^v^#=e1b8vm0@#0xqo5k5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',  
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Core',
    'Usuario',
    'Inventario',
    'Ventas.apps.VentasConfig',
    'rest_framework',
    'Pedidos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Whitenoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DATABIOS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DATABIOS.wsgi.application'


# Configuración de mensajes
from django.contrib.messages import constants as messages    # added by Diego

MESSAGE_TAGS = {                                             # added by Diego
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

AUTH_USER_MODEL = 'Core.Usuario'                            # added by Diego
LOGIN_REDIRECT_URL = '/usuarios/'                           # added by Diego
LOGOUT_REDIRECT_URL = '/usuarios/login/'                    # added by Diego
LOGIN_URL = '/usuarios/login/'                              # added by Diego



# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

try:
    import dj_database_url
    has_dj_database_url = True
except ImportError:
    has_dj_database_url = False

DATABASE_URL = os.environ.get('DATABASE_URL')

# 1. Opción Principal: Producción / URL de Base de Datos externa
if DATABASE_URL and has_dj_database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            )
    }
else:
    # Obtener el Host para verificar si es local o si existe la intención de usar Postgres
    db_host = os.environ.get('DB_HOST', 'localhost')
    
    # Condición: Si las variables de entorno de Postgres personalizadas existen o estás en producción local,
    # pero si estás en Codespaces sin Postgres iniciado, forzamos el fallback a SQLite.
    # Para entornos provisionales rápidos, si el HOST es localhost o 127.0.0.1, evaluamos usar SQLite.
    
    # 2. Opción Secundaria: PostgreSQL Local (Solo si no estamos en un entorno limpio de Codespaces o si se prefiere SQLite por defecto local)
    # NOTA: Puedes cambiar esta variable 'USE_LOCAL_POSTGRES' en tus variables de entorno si deseas forzarlo.
    if os.environ.get('USE_LOCAL_POSTGRES') == 'True' or (os.environ.get('CODESPACES') is None and db_host == 'localhost'):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': os.environ.get('DB_NAME', 'data_bios'),
                'USER': os.environ.get('DB_USER', 'gabri'),
                'PASSWORD': os.environ.get('DB_PASSWORD', 'gab'),
                'HOST': db_host,
                'PORT': os.environ.get('DB_PORT', '5432'),
            }
        }
    else:
        # 3. Opción de Fallback: SQLite (Ideal para GitHub Codespaces provisionales)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Destination for collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise storage configuration for caching/compressing static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Avoid deployment build failures due to broken static file references in CSS/JS
WHITENOISE_MANIFEST_STRICT = False

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
