# Generated by Django 5.0.6 on 2026-06-19 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConjuntoPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidos_pen_CUD', models.BooleanField(default=False)),
                ('pedidos_pen_S', models.BooleanField(default=False)),
                ('pedidos_rec_G', models.BooleanField(default=False)),
                ('inventario_cat_CUD', models.BooleanField(default=False)),
                ('inventario_pro_CUD', models.BooleanField(default=False)),
                ('inventario_pro_G', models.BooleanField(default=False)),
                ('ventas_CD', models.BooleanField(default=False)),
                ('panel_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='No Especificado', max_length=100)),
                ('ruc', models.CharField(max_length=9)),
                ('telefono', models.CharField(default='Sin Número', max_length=9)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado_registro', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('stock_min', models.IntegerField(default=10)),
                ('stock_max', models.IntegerField(default=20)),
                ('estado_registro', models.CharField(default='A', max_length=1)),
                ('categorias', models.ManyToManyField(to='Core.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('cancelado', 'Cancelado'), ('en_proceso', 'En Proceso'), ('entregado', 'Entregado')], default='en_proceso', max_length=20)),
                ('descripcion', models.CharField(default='Ninguno', max_length=200)),
                ('categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Core.categoria')),
                ('productos', models.ManyToManyField(to='Core.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=18)),
                ('apellido', models.CharField(max_length=18)),
                ('categoria', models.CharField(max_length=18)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_permisos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.conjuntopermisos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
